coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_not_found: success
    patch:
      default:
        target: 85%
        threshold: 5%
        if_not_found: success

  ignore:
    - "tests/"
    - "examples/"
    - "docs/"
    - "**/__init__.py"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true
