site_name: Neon CRM Python SDK
site_description: A comprehensive Python SDK for the Neon CRM API v2
site_author: Neon CRM SDK Team
repo_url: https://github.com/your-username/neon-crm-python

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Custom Fields: user-guide/custom-fields.md
    - Search & Filtering: user-guide/search.md
    - Error Handling: user-guide/error-handling.md
    - Caching: user-guide/caching.md
    - Logging: user-guide/logging.md
  - API Reference:
    - Client: api/client.md
    - Resources:
      - Accounts: api/resources/accounts.md
      - Donations: api/resources/donations.md
      - Events: api/resources/events.md
      - Custom Fields: api/resources/custom-fields.md
      - Custom Objects: api/resources/custom-objects.md
    - Exceptions: api/exceptions.md
    - Types: api/types.md
  - Examples:
    - Basic Examples: examples/basic.md
    - Custom Fields Examples: examples/custom-fields.md
  - Contributing: contributing.md
  - Changelog: changelog.md
